services:
  - type: web
    name: glbconnect
    env: node
    nodeVersion: 18.18.0
    buildCommand: |
      npm install
      cd client && npm install --legacy-peer-deps
      cd client && npm install vite@latest @vitejs/plugin-react@latest --save-dev
      cd ..
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
    buildPackages:
      - nodejs-18.18.0 